### ISSUE TITLE
Bad access exception on macOS

### ISSUE THREAD

**Issue by kkirby** [arturoc/ofxTextureRecorder#1]
I tried this on MacOS Sierra and I get an issue where all the threads are notified when a new frame comes in, which causes a bad access on all but one thread. I tried the example provided and this was the result. Am I missing something?

**Comment by arturoc** [comment]
are you using OF 0.9.8? in that case i think this is probably not compatible with that version, ofThreadChannel in 0.9.8 supports multiple producers single consumer. In current master or the nightly builds it supports multiple consumers to  so that's probably what's going on

**Comment by kkirby** [comment]
That'll do it, thanks!
