### ISSUE TITLE
Compiling errors VS2015

### ISSUE THREAD

**Issue by Meach** [arturoc/ofxTextureRecorder#2]
Hi,
I wanted to try this addon on Windows 10, with Visual Studio 2015 using OF0.9.8 version but it gives me tons of compilation errors.
Is it supposed to work on windows at all? If yes, do you need more info on the errors I am getting?

Cheers,

**Comment by arturoc** [comment]
yes it should but you might need to use OF master from github or the nightly builds, there' was a bug in windows but it should be fixed now, also you can check the current build state now in the readme
