### ISSUE TITLE
ofImageFormatExtension ?

### ISSUE THREAD

**Issue by stephanschulz** [arturoc/ofxTextureRecorder#3]
I guess this addon only for OF 0.10 ?
I am still at 0.9.8, since it's the last stable version.

i'm getting a comply error at line 224 saying:
````
/Applications/of_v0.9.8_osx_release/addons/ofxTextureRecorder/src/ofxTextureRecorder.cpp:224:64: Use of undeclared identifier 'ofImageFormatExtension'
````

**Comment by arturoc** [comment]
yes only works with nightly
